apiVersion: v1
kind: Service
metadata:
  name: gvb-mysql
  
  labels:
    app: gvb-mysql
spec:
  selector: 
    app: gvb-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
