apiVersion: v1
kind: Service
metadata:
  name: gvb-redis
  
  labels:
    app: gvb-redis
spec:
  selector: 
    app: gvb-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
