apiVersion: v1
kind: PersistentVolume
metadata:
  name: gvb-server-pv
  labels:
    type: local
  annotations:
    # "helm.sh/hook": pre-install,pre-upgrade
    # "helm.sh/hook-weight": "-6"

spec:
  storageClassName: {{ .Values.global.storageClass }}
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/gvb/server"