apiVersion: v1
kind: Service
metadata:
  name: gvb-server
  
  labels:
    app: gvb-server
spec:
  selector: 
    app: gvb-server
  ports:
    - protocol: TCP
      name: admin
      port: 8765
      targetPort: 8765
    - protocol: TCP
      name: blog
      port: 5678
      targetPort: 5678
  type: ClusterIP
