apiVersion: v1
kind: Service
metadata:
  name: gvb-front
  
  labels:
    app: gvb-front
spec:
  selector: 
    app: gvb-front
  ports:
    - protocol: TCP
      name: http
      port: 80
      nodePort: 30002
      targetPort: 80
    - protocol: TCP
      name: https
      port: 8443
      targetPort: 443
  type: NodePort
