apiVersion: v1
kind: ConfigMap
metadata:
  name: default-conf-template
data:
  default.conf.template: |
    server {
        listen 80;
        server_name ${SERVER_NAME};
        root /usr/share/nginx/html;

        ######### 反向代理 start ########
        # 后台接口
        location /api {
            proxy_pass http://${BACKEND_HOST}:${BACK_SERVER_PORT};
            # 获取真实 IP 
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $remote_addr;

            client_max_body_size 40M;
        }
        # 前台接口
        location /api/front {
            proxy_pass http://${BACKEND_HOST}:${FRONT_SERVER_PORT};
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $remote_addr;

            client_max_body_size 40M;
        }
        # Gin 处理静态资源, Nginx 反向代理 Gin (本地文件上传才需要)
        location /public/uploaded {
            proxy_pass http://${BACKEND_HOST}:${BACK_SERVER_PORT}/public/uploaded;
        }
        location /admin/public/uploaded {
            proxy_pass http://${BACKEND_HOST}:${BACK_SERVER_PORT}/public/uploaded;
        }
        ######### 反向代理 end ########

        ######### 静态资源 start ########
        location / {
            try_files $uri $uri/ /index.html;
        }
        location /admin {
            try_files $uri $uri/ /admin/index.html;
        }
        location ~ .*\.(js|json|css)$ {
            gzip on;
            gzip_static on; 
            gzip_min_length 1k;
            gzip_http_version 1.1;
            gzip_comp_level 9;
            gzip_types text/css application/javascript application/json;
            root /usr/share/nginx/html;
        }
        ######### 静态资源 end ########
    }