apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvb-mysql-pv-claim
  annotations:
    # "helm.sh/hook": pre-install,pre-upgrade
    # "helm.sh/hook-weight": "-4"
  
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
