name: Build and push gvb  backend demo images

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest

    steps:         
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Log in to the Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}




      - name: Build and push mysql-demo images
        uses: docker/build-push-action@v3.3.1
        with:
          context: ./src/deploy/build/mysql
          file: ./src/deploy/build/mysql/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/demo-gvb-mysql:${{ github.sha }}
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/demo-gvb-mysql:latest

      - name: Build and push server-demo images
        uses: docker/build-push-action@v3.3.1
        with:
          context: ./src/gin-blog-server
          file: ./src/gin-blog-server/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/demo-gvb-server:${{ github.sha }}
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/demo-gvb-server:latest